#!/bin/bash

echo "🌐 Kanban Board GUI 已啟動！"
echo "============================================================"
echo ""
echo "📍 訪問地址："
echo "   http://localhost:8080/kanban-gui.html"
echo ""
echo "📁 文件位置："
echo "   $(pwd)/kanban-gui.html"
echo ""
echo "🔧 使用說明："
echo "   1. 在瀏覽器打開上述網址"
echo "   2. 點擊「添加新項目」創建任務"
echo "   3. 拖曳或按鈕移動項目狀態"
echo "   4. 每 30 秒自動刷新"
echo ""
echo "⚠️  注意："
echo "   - 添加/移動項目會創建 kanban-command.json"
echo "   - 需要後端腳本處理命令並更新 kanban-board.json"
echo ""
echo "🛑 停止服務："
echo "   按 Ctrl+C 或運行：kill $(cat /tmp/kanban_server.pid 2>/dev/null)"
echo ""
echo "============================================================"
